name: quinzy

services:
  quinzy:
    build:
      context: .
      dockerfile: Dockerfile
    image: quinzy:latest
    container_name: quinzy
    networks:
      - proxy
    restart: unless-stopped
    expose:
      - "8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.quinzy.rule=Host(`${QUINZY_HOSTNAME?Set QUINZY_HOSTNAME in .env}`)"
      - "traefik.http.routers.quinzy.entrypoints=websecure"
      - "traefik.http.routers.quinzy.tls.certresolver=letsencrypt"
      - "traefik.http.services.quinzy.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
